import type { PropsCard } from "./types";


export const ramdomWords:Array<PropsCard> = [
    {
        id:0,
        state:false,
        word:"Amanecer",
        score:1,
        wasSuccessful:false
    },
    {
        id:1,
        state:false,
        word:"Brócoli",
        score:1,
        wasSuccessful:false
    },
    {
        id:2,
        state:false,
        word:"Cangrejo",
        score:1,
        wasSuccessful:false
    },
    {
        id:3,
        state:false,
        word:"Dócil",
        score:1,
        wasSuccessful:false
    },
    {
        id:4,
        state:false,
        word:"Esfera",
        score:1,
        wasSuccessful:false
    },
    {
        id:5,
        state:false,
        word:"Fósil",
        score:1,
        wasSuccessful:false
    },
    {
        id:6,
        state:false,
        word:"Gárgola",
        score:1,
        wasSuccessful:false
    },
    {
        id:7,
        state:false,
        word:"Hedor",
        score:1,
        wasSuccessful:false
    },
    {
        id:8,
        state:false,
        word:"Ígneo",
        score:1,
        wasSuccessful:false
    },
]